#SAM FILE

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Resume Website.
Resources:
  sitevisits:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: src/
      Description: A website visit tracker AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        Api:
          Type: Api
          Properties:
            Path: /visits
            Method: GET
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: website
        Type: String
      #On Demand Billing Mode
      #BillingMode: PAY_PER_REQUEST
      #Provisioned Billing Mode
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
