AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A visit tracker AWS Lambda function.
Resources:
  trackvisits:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: s3://rc-back/1600045369780c2e723c56900cdee43b
      Description: A visit tracker AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
          REGION_NAME:
            Ref: AWS::Region
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
      Events:
        Api:
          Type: Api
          Properties:
            Path: /visits
            Method: GET
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: visitor
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
